name: Onfline-Spigot
version: 3.0
main: sakura.kooi.Onfline.spigot.OnflineSpigot
authors: [SakuraKooi]
depend: [SakuraUtils]

commands:
    onfline:
        description: 'Request a Onfline online check to bungeecord'
        aliases: [zb]
        
permissions:
    onfline.use:
        default: true
