name: Onfline-Spigot
version: 2.0
main: ldcr.Onfline.spigot.OnflineSpigot
authors: [Ldcr]
depend: [LdcrUtils]

commands:
    onfline:
        description: 'Request a Onfline online check to bungeecord'
        aliases: [zb]
        
permissions:
    onfline.use:
        default: true
